name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set Terraform Environment Variables
        run: |
          echo "TF_VAR_client_id=${{ secrets.ARM_CLIENT_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_client_secret=${{ secrets.ARM_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "TF_VAR_subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "TF_VAR_tenant_id=${{ secrets.ARM_TENANT_ID }}" >> $GITHUB_ENV

          echo "ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }}" >> $GITHUB_ENV

      - name: Debug Environment Variables
        run: |
          echo "✅ Checking extracted credentials..."
          [ -z "$TF_VAR_client_id" ] && echo "❌ TF_VAR_client_id is EMPTY!" || echo "✅ TF_VAR_client_id: $TF_VAR_client_id"
          [ -z "$ARM_CLIENT_ID" ] && echo "❌ ARM_CLIENT_ID is EMPTY!" || echo "✅ ARM_CLIENT_ID: $ARM_CLIENT_ID"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Initialize Terraform
        run: terraform init -input=false
      
      - name: Terraform Plan
        run: |
          terraform plan -input=false \
            -var="client_id=$TF_VAR_client_id" \
            -var="client_secret=$TF_VAR_client_secret" \
            -var="subscription_id=$TF_VAR_subscription_id" \
            -var="tenant_id=$TF_VAR_tenant_id"

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve -input=false \
            -var="client_id=$TF_VAR_client_id" \
            -var="client_secret=$TF_VAR_client_secret" \
            -var="subscription_id=$TF_VAR_subscription_id" \
            -var="tenant_id=$TF_VAR_tenant_id"
