name: Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Extract Azure Credentials
        run: |
          echo "TF_VAR_client_id=$(jq -r '.clientId' <<< '${{ secrets.AZURE_CREDENTIALS }}')" >> $GITHUB_ENV
          echo "TF_VAR_client_secret=$(jq -r '.clientSecret' <<< '${{ secrets.AZURE_CREDENTIALS }}')" >> $GITHUB_ENV
          echo "TF_VAR_subscription_id=$(jq -r '.subscriptionId' <<< '${{ secrets.AZURE_CREDENTIALS }}')" >> $GITHUB_ENV
          echo "TF_VAR_tenant_id=$(jq -r '.tenantId' <<< '${{ secrets.AZURE_CREDENTIALS }}')" >> $GITHUB_ENV

          echo "ARM_CLIENT_ID=$(jq -r '.clientId' <<< '${{ secrets.AZURE_CREDENTIALS }}')" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=$(jq -r '.clientSecret' <<< '${{ secrets.AZURE_CREDENTIALS }}')" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=$(jq -r '.subscriptionId' <<< '${{ secrets.AZURE_CREDENTIALS }}')" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=$(jq -r '.tenantId' <<< '${{ secrets.AZURE_CREDENTIALS }}')" >> $GITHUB_ENV

      - name: Debug Environment Variables
        run: |
          echo "TF_VAR_client_id: $TF_VAR_client_id"
          echo "ARM_CLIENT_ID: $ARM_CLIENT_ID"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var="client_id=$TF_VAR_client_id" \
                            -var="client_secret=$TF_VAR_client_secret" \
                            -var="subscription_id=$TF_VAR_subscription_id" \
                            -var="tenant_id=$TF_VAR_tenant_id"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="client_id=$TF_VAR_client_id" \
                                               -var="client_secret=$TF_VAR_client_secret" \
                                               -var="subscription_id=$TF_VAR_subscription_id" \
                                               -var="tenant_id=$TF_VAR_tenant_id"
